### PR TITLE
Update Vue example in README.md

### PR DESCRIPTION
**Pull request by edbond88**

### CODE REVIEW

**Review by rektdeckard — APPROVED** [review]
Thanks, I missed that!

**Review by rektdeckard — CHANGES_REQUESTED** [review]
Actually, on second thought I don't like the change to PascalCase components in the template. It may look nicer, but it is less safe (invalid if authoring Vue content directly in the DOM, using CDN version of Vue for example), and less common as I understand it.

**Comment by edbond88** [comment]
In Vue [documentation](https://vuejs.org/guide/essentials/component-basics.html) mostly used PascalCase

image

**Comment by rektdeckard** [comment]
I read this as
kebab-case: compatible with everything, including DOM-authored Vue apps
PascalCase: only compatible with precompiled Vue apps

I'm not a big Vue user, so I am happy to defer to your judgement if you feel like every Vue dev knows these caveats, and it's not necessary to write docs in the most compatible style.

**Comment by edbond88** [comment]
Yea I think most of Vue devs understand this examples

**Review by rektdeckard — APPROVED** [review]

**Pull request merged**
