### PR TITLE
chore(docs): list phosphor-css in community projects

### PR DESCRIPTION
**Pull request by lucagoslar**

### CODE REVIEW

**Comment by rektdeckard** [comment]
I quite like this implementation! Will take a further look and demo it tonight before adding. But thanks for the contribution!

**Comment by rektdeckard** [comment]
Exactly what I was hoping for in publishing the core package :)

**Comment by lucagoslar** [comment]
Fantastic, thanks!

**Comment by lucagoslar** [comment]
Found a bug - I missed adding a dollar sign, breaking most SASS and CSS behaviour. You can find a demo at https://github.com/lucagoslar/phosphor-css-demo-pr-209, which I deployed to https://lucagoslar.github.io/phosphor-css-demo-pr-209/.

**Comment by lucagoslar** [comment]
My apologies.

**Comment by rektdeckard** [comment]
@lucagoslar thanks for the fix, I was having trouble testing weights other than `regular` on my end and thought I was doing something wrong 😅. Testing again...

**Comment by rektdeckard** [comment]
I had one small comment. Not to tell you how to make your lib, but I have a feeling that using compound class selectors `.ph.train.duotone` might lead to some unintentional styles being applied, since the individual class names are so simple. That's why we used atomic classes like `ph-train-duotone` in our implementation, to try to avoid clashing`.

**Comment by rektdeckard** [comment]
Also, out of curiosity, is it possible to color the icons without resorting to CSS image filters?

**Comment by lucagoslar** [comment]
Fair point. However, ‘.train’ has no effect without ‘.ph’. So, unless one is using ‘.ph’ for another purpose, there should be no trouble. In addition, using exclusively atomic classes would not allow reusing styles, producing a much larger output. How about ‘.ph.icon’ instead?

**Comment by lucagoslar** [comment]
Excellent idea. This could work using a [mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) instead of a background image - using filters might not be necessary. I will be taking care of this in the future.

**Pull request merged**
